// Copyright (c) 2018, ZIH,
// Technische Universitaet Dresden,
// Federal Republic of Germany
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright notice,
//       this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright notice,
//       this list of conditions and the following disclaimer in the documentation
//       and/or other materials provided with the distribution.
//     * Neither the name of metricq nor the names of its contributors
//       may be used to endorse or promote products derived from this software
//       without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: history.proto

package metricq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryRequest_RequestType int32

const (
	// Timeline of aggregates over |start_time, end_time[ with the specified interval_max
	HistoryRequest_AGGREGATE_TIMELINE HistoryRequest_RequestType = 0
	// Single aggregate value over [start_time, end_time[ in aggregates
	HistoryRequest_AGGREGATE HistoryRequest_RequestType = 1
	// Single last value in values (0 values if no values in DB)
	HistoryRequest_LAST_VALUE HistoryRequest_RequestType = 2
	// Either aggregates or values in |start_time, end_time[ depending on the specified interval_max
	HistoryRequest_FLEX_TIMELINE HistoryRequest_RequestType = 3
)

// Enum value maps for HistoryRequest_RequestType.
var (
	HistoryRequest_RequestType_name = map[int32]string{
		0: "AGGREGATE_TIMELINE",
		1: "AGGREGATE",
		2: "LAST_VALUE",
		3: "FLEX_TIMELINE",
	}
	HistoryRequest_RequestType_value = map[string]int32{
		"AGGREGATE_TIMELINE": 0,
		"AGGREGATE":          1,
		"LAST_VALUE":         2,
		"FLEX_TIMELINE":      3,
	}
)

func (x HistoryRequest_RequestType) Enum() *HistoryRequest_RequestType {
	p := new(HistoryRequest_RequestType)
	*p = x
	return p
}

func (x HistoryRequest_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryRequest_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_history_proto_enumTypes[0].Descriptor()
}

func (HistoryRequest_RequestType) Type() protoreflect.EnumType {
	return &file_history_proto_enumTypes[0]
}

func (x HistoryRequest_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryRequest_RequestType.Descriptor instead.
func (HistoryRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{0, 0}
}

type HistoryRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	StartTime     int64                      `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                      `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IntervalMax   int64                      `protobuf:"varint,3,opt,name=interval_max,json=intervalMax,proto3" json:"interval_max,omitempty"`
	Type          HistoryRequest_RequestType `protobuf:"varint,4,opt,name=type,proto3,enum=metricq.HistoryRequest_RequestType" json:"type,omitempty"` // default: AGGREGATE_TIMELINE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *HistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *HistoryRequest) GetIntervalMax() int64 {
	if x != nil {
		return x.IntervalMax
	}
	return 0
}

func (x *HistoryRequest) GetType() HistoryRequest_RequestType {
	if x != nil {
		return x.Type
	}
	return HistoryRequest_AGGREGATE_TIMELINE
}

type HistoryResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Metric    string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	TimeDelta []int64                `protobuf:"varint,2,rep,packed,name=time_delta,json=timeDelta,proto3" json:"time_delta,omitempty"`
	// Deprecated: Marked as deprecated in history.proto.
	ValueMin []float64 `protobuf:"fixed64,3,rep,packed,name=value_min,json=valueMin,proto3" json:"value_min,omitempty"`
	// Deprecated: Marked as deprecated in history.proto.
	ValueMax []float64 `protobuf:"fixed64,4,rep,packed,name=value_max,json=valueMax,proto3" json:"value_max,omitempty"`
	// Deprecated: Marked as deprecated in history.proto.
	ValueAvg      []float64                    `protobuf:"fixed64,5,rep,packed,name=value_avg,json=valueAvg,proto3" json:"value_avg,omitempty"`
	Aggregate     []*HistoryResponse_Aggregate `protobuf:"bytes,6,rep,name=aggregate,proto3" json:"aggregate,omitempty"`
	Value         []float64                    `protobuf:"fixed64,7,rep,packed,name=value,proto3" json:"value,omitempty"`
	Error         string                       `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *HistoryResponse) GetTimeDelta() []int64 {
	if x != nil {
		return x.TimeDelta
	}
	return nil
}

// Deprecated: Marked as deprecated in history.proto.
func (x *HistoryResponse) GetValueMin() []float64 {
	if x != nil {
		return x.ValueMin
	}
	return nil
}

// Deprecated: Marked as deprecated in history.proto.
func (x *HistoryResponse) GetValueMax() []float64 {
	if x != nil {
		return x.ValueMax
	}
	return nil
}

// Deprecated: Marked as deprecated in history.proto.
func (x *HistoryResponse) GetValueAvg() []float64 {
	if x != nil {
		return x.ValueAvg
	}
	return nil
}

func (x *HistoryResponse) GetAggregate() []*HistoryResponse_Aggregate {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *HistoryResponse) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HistoryResponse_Aggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minimum       float64                `protobuf:"fixed64,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum       float64                `protobuf:"fixed64,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Integral      float64                `protobuf:"fixed64,5,opt,name=integral,proto3" json:"integral,omitempty"`
	ActiveTime    int64                  `protobuf:"varint,6,opt,name=active_time,json=activeTime,proto3" json:"active_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse_Aggregate) Reset() {
	*x = HistoryResponse_Aggregate{}
	mi := &file_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse_Aggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse_Aggregate) ProtoMessage() {}

func (x *HistoryResponse_Aggregate) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse_Aggregate.ProtoReflect.Descriptor instead.
func (*HistoryResponse_Aggregate) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HistoryResponse_Aggregate) GetMinimum() float64 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *HistoryResponse_Aggregate) GetMaximum() float64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *HistoryResponse_Aggregate) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *HistoryResponse_Aggregate) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistoryResponse_Aggregate) GetIntegral() float64 {
	if x != nil {
		return x.Integral
	}
	return 0
}

func (x *HistoryResponse_Aggregate) GetActiveTime() int64 {
	if x != nil {
		return x.ActiveTime
	}
	return 0
}

var File_history_proto protoreflect.FileDescriptor

var file_history_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x71, 0x22, 0xff, 0x01, 0x0a, 0x0e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x12, 0x37, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x71,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x57, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x47, 0x47, 0x52,
	0x45, 0x47, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x41, 0x53, 0x54, 0x5f,
	0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x4c, 0x45, 0x58, 0x5f,
	0x54, 0x49, 0x4d, 0x45, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x03, 0x22, 0xc0, 0x03, 0x0a, 0x0f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6d,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x42, 0x02, 0x18, 0x01, 0x52, 0x08, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f,
	0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x42, 0x02, 0x18, 0x01, 0x52, 0x08, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x1f, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x61, 0x76, 0x67, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x42, 0x02, 0x18, 0x01, 0x52, 0x08,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x41, 0x76, 0x67, 0x12, 0x40, 0x0a, 0x09, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x71, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52,
	0x09, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0xa4, 0x01, 0x0a, 0x09, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_history_proto_rawDescOnce sync.Once
	file_history_proto_rawDescData []byte
)

func file_history_proto_rawDescGZIP() []byte {
	file_history_proto_rawDescOnce.Do(func() {
		file_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)))
	})
	return file_history_proto_rawDescData
}

var file_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_history_proto_goTypes = []any{
	(HistoryRequest_RequestType)(0),   // 0: metricq.HistoryRequest.RequestType
	(*HistoryRequest)(nil),            // 1: metricq.HistoryRequest
	(*HistoryResponse)(nil),           // 2: metricq.HistoryResponse
	(*HistoryResponse_Aggregate)(nil), // 3: metricq.HistoryResponse.Aggregate
}
var file_history_proto_depIdxs = []int32{
	0, // 0: metricq.HistoryRequest.type:type_name -> metricq.HistoryRequest.RequestType
	3, // 1: metricq.HistoryResponse.aggregate:type_name -> metricq.HistoryResponse.Aggregate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_history_proto_init() }
func file_history_proto_init() {
	if File_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_history_proto_goTypes,
		DependencyIndexes: file_history_proto_depIdxs,
		EnumInfos:         file_history_proto_enumTypes,
		MessageInfos:      file_history_proto_msgTypes,
	}.Build()
	File_history_proto = out.File
	file_history_proto_goTypes = nil
	file_history_proto_depIdxs = nil
}
